import os
from pathlib import Path

MODEL_PATH = "yolo11n.pt"
CAMERA_INDEX = 0
WINDOW_NAME = "YOLO detector"
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
FULLSCREEN = False

SAVE_DIR = Path("snapshots")
ARCHIVE_DIR = Path("archives")

PERSON_CONFIDENCE_THRESHOLD = 0.75
SNAPSHOT_AFTER_SECONDS = 0.2
SNAPSHOT_COOLDOWN_SECONDS = 2

SEND_EMAIL = True
SEND_TELEGRAM = True
REPORT_EVERY_SECONDS = 30

EMAIL_FROM = os.getenv("YOLO_EMAIL_FROM", "")
EMAIL_PASSWORD = os.getenv("YOLO_EMAIL_PASSWORD", "")
EMAIL_TO = os.getenv("YOLO_EMAIL_TO", "")
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

TELEGRAM_BOT_TOKEN = os.getenv("YOLO_TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("YOLO_TELEGRAM_CHAT_ID", "")