apiVersion: v1
kind: Secret
metadata:
  name: yolo-detector
  namespace: yolo-detector
stringData:
  YOLO_EMAIL_FROM: ''
  YOLO_EMAIL_PASSWORD: ''
  YOLO_EMAIL_TO: ''
  YOLO_TELEGRAM_BOT_TOKEN: ''
  YOLO_TELEGRAM_CHAT_ID: ''
